# This rule is not used by the project controlplane-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to controlplane.kplane.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controlplane-operator
    app.kubernetes.io/managed-by: kustomize
  name: controlplaneclass-viewer-role
rules:
- apiGroups:
  - controlplane.kplane.dev
  resources:
  - controlplaneclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controlplane.kplane.dev
  resources:
  - controlplaneclasses/status
  verbs:
  - get
